Word.create(english: 'apple', german: 'Apfel', article: 'der')
Word.create(english: 'house', german: 'Haus', article: 'das')
Word.create(english: 'cat', german: 'Katze', article: 'die')
Word.create(english: 'dog', german: 'Hund', article: 'der')
Word.create(english: 'table', german: 'Tisch', article: 'der')
Word.create(english: 'chair', german: 'Stuhl', article: 'der')
Word.create(english: 'book', german: 'Buch', article: 'das')
Word.create(english: 'window', german: 'Fenster', article: 'das')
Word.create(english: 'door', german: 'Tür', article: 'die')
Word.create(english: 'car', german: 'Auto', article: 'das')
Word.create(english: 'coffee', german: 'Kaffee', article: 'der')
Word.create(english: 'tea', german: 'Tee', article: 'der')
Word.create(english: 'water', german: 'Wasser', article: 'das')
Word.create(english: 'brother', german: 'Bruder', article: 'der')
Word.create(english: 'sister', german: 'Schwester', article: 'die')
Word.create(english: 'flower', german: 'Blume', article: 'die')
Word.create(english: 'tree', german: 'Baum', article: 'der')
Word.create(english: 'sun', german: 'Sonne', article: 'die')
Word.create(english: 'moon', german: 'Mond', article: 'der')
Word.create(english: 'sky', german: 'Himmel', article: 'der')
Word.create(english: 'ball', german: 'Ball', article: 'der')
Word.create(english: 'pharmacy', german: 'Apotheke', article: 'die')
Word.create(english: 'doctor', german: 'Arzt', article: 'der')
Word.create(english: 'school', german: 'Schule', article: 'die')
Word.create(english: 'friend', german: 'Freund', article: 'der')

puts Word.count
